### ISSUE TITLE
"Programming in Ada 2012" is not the language reference!

### ISSUE THREAD

**Issue by sparre** [ohenley/awesome-ada#10]
The textbook "Programming in Ada 2012" is definitely **not** the language reference.  It is possibly the most comprehensive Ada 2012 textbook, but it is still only a textbook.

Technically, I think you can get the official "Ada Language Reference" for Ada 2012 in print from Springer, but check it out.

**Comment by ohenley** [comment]
Changed to Comprehensive reference. Is it ok?

**Comment by ohenley** [comment]
Changing for : Comprehensive

**Comment by ohenley** [comment]
I hope you well sparre, really. I am closing as I know you might not answer often.
