### ISSUE TITLE
Issues reported by awesome-lint

### ISSUE THREAD

**Issue by mgrojo** [ohenley/awesome-ada#107]
The awesome-lint program has run for the first time; I wasn't aware of those issues. It seems the link checker was aborting the action. 

https://github.com/ohenley/awesome-ada/actions/runs/4267389929/jobs/7428942700

There are some legitimate and important issues to be fixed:
- Double links in the Contents (only first one will work).
- Double links due to incorrect copy-paste for a book.

Other puristic ones, but easy to solve.

A few looks like there's some bug in awesome-lint.

And finally, other ones that I'm not sure if they should be solved: either because they would affect presentation or because we would lose something, like a second link to the same URL. It doesn't like either the out-of-place links that I precisely included to centralize the URL, so I don't see a solution for those.

I'll try to clean the important and easy ones, and we should discuss the remaining: whether there's a way to fix them, the rule can be disabled or the lint has to be removed altogether.

**Comment by mgrojo** [comment]
I directly fixed the non-controversial issues and have made pull requests with the ones requiring review. 

These are the only remaining issues if everything is merged:
```
README.md:1:1:   The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome-github
```
This can be solved adding the corresponding tag, that can only be done by the owner.

```
README.md:194:3:   https://matrix.to/#/#ada-lang_Lobby:gitter.im                remark-lint:double-link
README.md:202:112: https://matrix.to/#/#ada-lang:matrix.org                     remark-lint:double-link
```
These seem like a bug in how the linter interprets URLs. See https://github.com/Scrum/remark-lint-double-link/pull/10

**Comment by mgrojo** [comment]
There's still a pending issue reported by the linter:

  README.md:1:1
  ✖  1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome-github

@ohenley I think this can only be fixed by you.

**Comment by ohenley** [comment]
Yep missed it. Did add "awesome-list" as a GitHub topic.

**Comment by mgrojo** [comment]
Great! Everything is passing now, except a timeout in https://www.ada-europe.org/ which I hope is a transitory problem. Closing this, thanks.
