### ISSUE TITLE
Error with https://www.ada-europe.org/ (unable to get local issuer certificate)

### ISSUE THREAD

**Issue by mgrojo** [ohenley/awesome-ada#115]
From the action results: https://github.com/ohenley/awesome-ada/actions/runs/5598882127/job/15166018598#step:4:49

* [ERR] [https://www.ada-europe.org/](https://www.ada-europe.org/) | Failed: Network error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921: (unable to get local issuer certificate)

I wonder why this is failing when Firefox and Chomium are completely happy with the security of the connection. If it keeps happening, we might want to switch to the HTTP URL.

**Comment by ohenley** [comment]
@mgrojo This is fixed, right? Can I close? Thx.

**Comment by mgrojo** [comment]
It's more worked-around than fixed (changed the link to http), but the real problem is in the server, as you can see in the related issue in lycheeverse. I already reported to the webmaster, but they haven't fixed it yet (just tested with `curl`). From our side, we can close the issue.
