### ISSUE TITLE
DNS error for adachess.com

### ISSUE THREAD

**Issue by mgrojo** [ohenley/awesome-ada#117]
Reported by the link checker:

* [ERR] [https://www.adachess.com/](https://www.adachess.com/) | Failed: Network error: dns error: no record found for Query { name: Name("www.adachess.com.0gmlufkfg3qedhhdqgiv5q0qyc.phxx.internal.cloudapp.net."), query_type: AAAA, query_class: IN }

There is no apparent replacement. There is https://www.chessprogramming.org/AdaChess but there's no access to source code. The Wayback Machine wouldn't allow either to download the source code: http://web.archive.org/web/20230622210311/https://www.adachess.com/

If someone has contact with the author, they could ask him if he's going to restore adachess.com, otherwise suggest him to upload the sources to any source code forge.

**Comment by mgrojo** [comment]
Hi @adachess, glad you're here.

Do you have any plan for the above-mentioned issue?

**Comment by adachess** [comment]
Hi, please sorry my late answer! I am moving the source code here on GitHub, you will find the updated version n. 4.0 soon. If you wish to get the source code sooner, just let me know and I can send you them via email or sharing a dropbox file. Greetings

**Comment by mgrojo** [comment]
Awesome! I'm glad to hear that you are preparing to put Adachess source online again soon. Just let us know so we can update the URL in the list. Best regards.

**Comment by adachess** [comment]
The repository is now public with the source and a zipped-executable for windows! Thanks for your patience and please enjoy play with AdaChess!

**Comment by mgrojo** [comment]
AdaChess won! :wink:
![imagen](https://github.com/ohenley/awesome-ada/assets/13812910/bf9a7ced-4b88-41a0-b79b-5d7494ad0184)

Thanks, I will update the list and close this issue.
