### ISSUE TITLE
Amatrix

### ISSUE THREAD

**Issue by jklmnn** [ohenley/awesome-ada#12]
[amatrix](https://github.com/jklmnn/amatrix) which is currently noted under Math is not a mathematical matrix library but a prototypical implementation of the [Matrix](https://matrix.org/blog/home/) protocol.
So instead of Math it should be under Algorithms, containers and protocols although I'd suggest to remove it completely from this list since it is far away from being usable for any serious project.

**Comment by ohenley** [comment]
thx for letting me know. I just removed it.
