### ISSUE TITLE
Pasta times out

### ISSUE THREAD

**Issue by mgrojo** [ohenley/awesome-ada#132]
The online-running Pasta game has been timing out for two weeks.
 https://github.com/ohenley/awesome-ada/actions/runs/9531842326

I didn't find another working URL nor the location of source code.

@zertovitch are you aware of that? If there is no longer a running version, it is not important for this list; a link to the source code will be enough, and even more appropriate.

**Comment by zertovitch** [comment]
Ouch!
Fixed now.
Fortunately the server can run for months without trouble.
Ideally it would run forever ;-)
Thanks for reporting!

**Comment by mgrojo** [comment]
Great! The link checker is perfect for detecting those cases.

**Comment by zertovitch** [comment]
Great! I bookmark that!
