### ISSUE TITLE
add stcarrez/ada-ado

### ISSUE THREAD

**Issue by gerr135** [ohenley/awesome-ada#20]
Back from Fosdem (a few days ago), and before I totally forget, I think this project should definitely be added to the list. The author of that depo was presenting and he is pretty awesome - he pretty much single-handedly translated Java Beans to Ada - that's the ada-awa depo you have linked to the list. However he also presented the ada-ado project. While this is used by ada-awa, this is a standalone project that may be very useful on its own. It goes beyond simple database binding. It actually creates typed data for each pulled in db entry. So yes, this is tied to that bigger project, but can be used standalone too for (more low level) db work. I think it would be useful to have a separate link for it.
The link to the project:
https://github.com/stcarrez/ada-ado

**Comment by ohenley** [comment]
Hey,

Yes I know all the amazing work from Stephane and it's on my to-do list.
I'll try to move fast on that because he should be in the way before many
projects already there.

Thanks for bringing that up. 😊

**Comment by gerr135** [comment]
Ack :)

**Comment by ohenley** [comment]
everything has been added. :)
