### ISSUE TITLE
This list should be in https://github.com/topics/awesome

### ISSUE THREAD

**Issue by mgrojo** [ohenley/awesome-ada#4]
This list should be in https://github.com/topics/awesome

If it follows the requirements:
https://github.com/sindresorhus/awesome/blob/master/create-list.md

A Pull Request to https://github.com/sindresorhus/awesome should be made.

See issue:
https://github.com/sindresorhus/awesome/issues/977

**Comment by ohenley** [comment]
1. Added to https://github.com/topics/awesome
2. Followed requirements
3. Created pull request: https://github.com/sindresorhus/awesome/pull/1482
