### ISSUE TITLE
Broken link for "lib-anne" in "Algorithms, Containers and Protocols"

### ISSUE THREAD

**Issue by bogen85** [ohenley/awesome-ada#53]
In [Algorithms, Containers and Protocols](https://github.com/ohenley/awesome-ada#algorithms-containers-and-protocols)
    [lib-anne](https://github.com/Entomy/libAnne) - Large collection of Ada packages. This is sort of meant to be a "new standard library". Who's Anne? Ada's daughter.

The ```lib-anne``` repository is no longer available. The author still has a github page [Entomy](https://github.com/Entomy) but the ```lib-anne``` repository is no longer visible on it.

**Comment by bogen85** [comment]
The following link from [Entomy](https://github.com/Entomy) is also broken:

#### Unit Test, Testing
- [testing](https://github.com/Entomy/Testing) - Ada unit testing and measuring framework.

**Comment by ohenley** [comment]
Just removed the dead links: https://github.com/ohenley/awesome-ada/commit/f0e3df247119dd3730c4bda6cac0e0c3fd93087c

Thanks for the heads up Bogan85.
