### ISSUE TITLE
PowerJoular

### ISSUE THREAD

**Issue by adelnoureddine** [ohenley/awesome-ada#93]
Hi, could you consider adding my power monitoring tool, [PowerJoular](https://www.noureddine.org/research/joular/powerjoular) to the list?
It's a Linux multi-platform tool (x86_64, ARM/Raspberry Pi) to monitor the power consumption of hardware and software components (process, CPU, GPU).
It's fully written in Ada, open source under GPL 3, and available as a crate in Alire.

**Comment by ohenley** [comment]
Sure!
