### ISSUE TITLE
Invisible logo on Firefox

### ISSUE THREAD

**Issue by mgrojo** [ohenley/awesome-ada#97]
The new logo added in 43a355f34830214a7948ab04ba625178e26f2b42 cannot be displayed on Firefox browser.

**Comment by ohenley** [comment]
IMO, Firefox is definitely overrated. I will install Firefox and look into it. Thx @mgrojo.

**Comment by mgrojo** [comment]
It might be Firefox's fault, but also something not very standard compliant in the image. Look, for example, how it is displayed by the `eog` image viewer:

![imagen](https://user-images.githubusercontent.com/13812910/209173257-3b3622c5-84ba-481d-8700-ea63fe91d761.png)

Both applications usually work well for SVG, but who knows. The W3C validator only raises two warnings, but one of them it's to warn about not analysing part of the file: https://validator.w3.org/check?uri=https%3A%2F%2Fraw.githubusercontent.com%2Fohenley%2Ffiles%2Fmaster%2Fawesome-ada%2Fawesome_ada_logo.svg&charset=%28detect+automatically%29&doctype=Inline&group=0

**Comment by mgrojo** [comment]
It's funny. In `eog` if you change the grid pattern by a black background, it displays correctly, with a white background it disappears completely. Firefox, on the other hand, behaves the same with a clear or a dark github theme.

**Comment by ohenley** [comment]
Can you reload it/download. I fixed on my side using eog and then modified the file on github.
I add to remove mode="lighten". 
Inkscape left that in for what ever reason.

**Comment by mgrojo** [comment]
Yes, I can see it now. Good work!
